name:                natural-sort
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ryantm/natural-sort#readme
license:             BSD3
author:              Ryan Mulligan
maintainer:          ryan@ryantm.com
copyright:           2017 Ryan Mulligan
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - tasty

executables:
  natural-sort:
    source-dirs:      src
    main:             Main.hs

tests:
  test:
    source-dirs:      test
    main:             Main.hs
